version: '3.8'

services:
  # Go后端服务
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - GIN_MODE=release
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./server:/app
    restart: unless-stopped
    networks:
      - pixel-chat-network

  # React前端服务
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - pixel-chat-network

networks:
  pixel-chat-network:
    driver: bridge
